### ISSUE TITLE
A project can connect to a dictionary from another chain

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#1309]
### Description

Recently came to an issue where a project was connected to a production mainnet, but had the testnet dictionary linked to it. The project started running fine but nothing indexed because the testnet dictionary was returning blocks that it thought had events in them, but the project was discarding them when inspected deeper.

When the project starts, you should check that both the `endpoint` and the `dictionary._metadata.genesisHash` matches the chainID in project manifest and abort if otherwise with an error

**Comment by jiqiang90** [comment]
We have this logic in the implementation already,  rather than throw an error and stop indexing, we prefer continue indexing without dictionary and print warnings. 

However, you get a point, might be the warning isn't friendly enough to indicates the reason of why dictionary is invalid. 

https://github.com/subquery/subql/blob/37bce4001e3a716e5b95c478decb29ee1ea22018/packages/node/src/indexer/fetch.service.ts#L573
