### ISSUE TITLE
Worker threads support for unfinalized blocks

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#1399]

**Comment by kumar8317** [comment]
@stwiname  I got error while trying to use workers feature to index blocks in subquery. Multiple block_range blocks are missing, getting error -cannot query unfinalized data

![image](https://user-images.githubusercontent.com/94622810/203131570-d9e96aee-75e9-4b50-b2cf-e8367455ca74.png)
![image](https://user-images.githubusercontent.com/94622810/203131720-16c249ae-ad55-4202-8e74-340e460f65d1.png)

**Comment by kumar8317** [comment]
@stwiname update on above issue. When running indexer with workers enabled, in fetchBlock function in worker.ts file, it is receiving [number] instead of number(height) because of which fetchBlock service is failing.

On including below fix ,above error seems to be fixed

![image](https://user-images.githubusercontent.com/94622810/203487563-a2e07a11-7aec-41ee-a197-414c3e295cee.png)


Could you check if this is a valid issue and fix and why its behaving like this in case of workers
