### ISSUE TITLE
`subql build` doesn't generate minified code

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#1676]
### Description

`subql build` or `subql build --mode=production` supposed to generate minified js output, but it's not.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** 
subql --version
@subql/cli/2.0.0 darwin-arm64 node-v18.16.0

**Comment by jiqiang90** [comment]
This is due to we still need beautify here. https://github.com/subquery/subql/blob/6e7d4ff6ab6eb4169e3ff792d4fb3d572d35cf84/packages/cli/src/controller/build-controller.ts#LL26C13-L26C21

And it is introduced here, https://github.com/subquery/subql/pull/1569, we need it to generate sourceMap in order to get stack trace.
