### ISSUE TITLE
Use poi table blockHash to improve unfinalized block accuracy 

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#1851]
### Prerequisites

* [ ] Are you running the latest version(s)?
* [ ] Have you searched the [documentation for your issue](https://academy.subquery.network/)?
* [ ] Did you search for an existing issue or pull request?

### Description

If a project enabled poi feature and unfinalized block, because some networks there are no such block number for block confirmation, 

if the last verifiable unfinalize block is still not match with on chain block hash, we can reverse find any poi block below this height, and find the closest finalized block. 

To do this, rather return header here https://github.com/subquery/subql/blob/main/packages/node-core/src/indexer/unfinalizedBlocks.service.ts#L202, we can add logic to trace back poi table.

### Details

These details can help to reproduce the environment the issue is occurring

**Local Environment:** [You can get this information from executing `subql version`.]
**Query Version:** [What is the version of the query service?]
**Indexer Version:** [What is the version of the indexer service?]
**Network Details:**
  * [Network]
  * [Block height, a block height where the issue is happening]
  * [Dictionary endpoint, if used]

### Steps to Reproduce

1. [First Step]
2. [Second Step]
3. [and so on...]

**Example project:** [A link to a minimal example that can reproduce the issue]

**Expected behavior:** [What you expected to happen]

**Actual behavior:** [What actually happened]

### Any other information

Is there any other information you would like to add?

**Comment by stwiname** [comment]
After further discussion with @jiqiang90 we think the problem resides elsewhere.

In the context of the unfinalized blocks service everything is working fine. The problem arises with the finalization checks for the ethereum sdk where chains that don't support the "finalized" block tag rely on a `blockConfirmations` variable. This is where we consider "latest" -  `blockConfirmations` to be the finalized block. If this block is not actually finalized because `blockConfirmations` is too low then we will run into issues with data correctness.

Further research is required in order to improve how we consider blocks finalized with the Ethereum SDK.

**Comment by ianhe8x** [comment]
No matter how many blockConfirmations we set, there's chance we don't have the block(hash) where the fork happened. This issue is to address this, and avoid the consequence when it happens, the people have different poi.

**Comment by stwiname** [comment]
This can be closed as ethereum SDK now does this with chains that have probabilistic finalization
