### ISSUE TITLE
fix the timing we do metadata preload

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#210]
After investigation of an issue, I find what we were doing is wrong, to be specific that we call `api.getBlockRegistry` to load and cache metadata when we detect a specVersion change.

The correct thing to do is compare parent block's specVersion, since current block is run on the code stored in parent block's storage.

Another place is affected by this issue is the specVersion we wrapped in SubstrateBlock object. I'm not sure if anyone is using it at the moment, but just think about the reason why we wrapped it there. there's two,
1. it is used by specVersion filter
2. it is exposed to mapping function so developer can do special treatments for a special specVersion

Both cases I think make more sense if this specVersion is the parent block's specVersion instead of current block's, because that is actually the one indicating which runtime code this block is running.

**Comment by zhex** [comment]
> since current block is run on the code stored in parent block's storage.

any document can provide on this?

**Comment by ianhe8x** [comment]
The video you post! and that's also what `@polkadot/api` does (https://github.com/polkadot-js/api/blob/e4c3289ad89311e3007665ed26e81468f0eec723/packages/api/src/base/Init.ts#L129) 

Here it uses header's parentHash to query specVersion

**Comment by zhex** [comment]
From my understanding via the video,  the block should run on its own spec version, not its parent; the upgrade always happens at the very beginning of the block, then go to the initialize phase and then run the rest of the block code.

from the `getBlockRegistry` code, it uses parentHash because in the range they give, the parent block and current block always has the same spec version.
