### ISSUE TITLE
sandbox whitelist

### ISSUE THREAD

**Issue by ntduan** [subquery/subql#230]
I want to query some off-chain data while processing event data and write them together to the database. But I found that I can't call third party dependencies. I would like to know if there is a way to configure my own whitelist, or if there is another way to solve this problem

**Comment by ianhe8x** [comment]
We want to make sure the indexing result is deterministic, therefore can't allow off-chain data participate the process.

I suggest you see the graphql endpoint of subquery as one of datasource of your dapp (not the only one), and combine these on-chain and off-chain data in your own application.

You can also try Apollo federation which supports some advanced usage to achieve that.

**Comment by ntduan** [comment]
Ok, I will try to solve this problem externally. 

But I think there is no way to avoid off-chain data. For example, you need to get the abi of the contract to resolve the events of the contract.

**Comment by ianhe8x** [comment]
Of course we will provide a solution for contracts, and I won't category abi same as other external data like token trading price. Abi is metadata of your on-chain contract, just like the additional types we ask you to provide in project.yaml. It could be even stored on-chain, I roughly remember there was a discussion around this topic.

**Comment by ilionic** [comment]
@ianhe8x I am getting an error 
```
ERROR failed to index block at height 1 handleCall() VMError: The module '@polkadot/util' is not whitelisted in VM.
```
Please suggest the way calling polkadot utils.

**Comment by ianhe8x** [comment]
`@polkadot/*` can be white labeled, I will add it soon.

**Comment by ianhe8x** [comment]
@ilionic It turns out more difficult than I thought, whitelisting it will lead to an error 
```
/..../node_modules/@polkadot/util/index.js:3
import "./detectPackage.js";
^^^^^^

SyntaxError: Cannot use import statement outside a module
```
due to a recent change since @polkadot/api v4.x, that build esm as default format.

An alternative way we can do it is inject `@polkadot/util` from host context to global so you can have access to its functions in sandbox.

Can you provide details of your use case why any function in `@polkadot/util` is required?

**Comment by ilionic** [comment]
Thanks for looking into it. I actually ended up with custom GraphQL solution due to additional indexer requirements and dependencies. Plus I need Subscribtion API. 

 > Can you provide details of your use case why any function in @polkadot/util is required?

My use case is to parse / validate certain metadata from blocks, so I need some polkadot utils like `u8aToHex, hexToString, stringToHex`

**Comment by yooml** [comment]
when I want to do some data processing:
`subquery-node_1   | [IndexerManager] failed to handler block 1, error: The module 'bn.js' is not whitelisted in VM.
`

**Comment by ianhe8x** [comment]
@yooml We don't allow 3rd lib used in the subquery project. For your case, you can use typescript's build-in bigint type.

**Comment by ianhe8x** [comment]
The new release `@subql/node@0.13.0` brings support for 3rd libs. It's experimental at the moment but we will keep improving it for sure.

**Comment by ianhe8x** [comment]
@here pls check `@subql/node@0.14.0`, libs like `@polkadot/util` (default to esm) are now supported. For commonjs libs, 0.13.0 already provided support. Therefore i'm closing this issue.
