### ISSUE TITLE
[node] use custom rpc

### ISSUE THREAD

**Issue by yooml** [subquery/subql#252]
when I want to use a custom rpc method, it looks problematic：
`Property 'zenlinkProtocol' does not exist on type 'DecoratedRpc<"promise", RpcInterface>'.ts(2339)
`

**Comment by ianhe8x** [comment]
We want to make sure the output of each processed block is deterministic, therefore we made a few changes to the api instance exposed in the global. details are stated here https://doc.subquery.network/create/define_a_subquery.html#query-states

Basically, we only allow you do states query, and the query will be replaced to query at current processing block.
Rpcs are removed since we can't tell if it will break the rule about determinacy

**Comment by ianhe8x** [comment]
use `@subql/node` >= 0.14.0
Also do remember to define your rpc definition in project.yaml (only rpc with historical parameter can be called). Check it out https://github.com/subquery/subql-examples/blob/main/kitty/project.yaml
