### ISSUE TITLE
Is there support for querying a snapshot of the index at a past block height?

### ISSUE THREAD

**Issue by theodorebugnet** [subquery/subql#339]
We are considering integrating SubQuery, and for our purposes it would be extremely helpful to be able to query the state at a particular block height, for historic data. However, I'm afraid I didn't find a clear answer in the docs - is there support built in for such a feature? Or would that have to be implemented manually, e.g. by adding a `Date` field to all relevant entities and then using that field for filtering in queries?

For instance, in the kitty example from the docs, consider a kitty where `owner = A` at block 1000. Then the kitty is transferred at block 1001, and the `handleKittyTransferred` mapping is called, updating the entity's `owner`. _Without_ manually adding e.g. an array of previous owners to the entity to keep track, is there any way to query which account was the owner of the kitty at block 1000?

**Comment by jamesbayly** [comment]
Hi @theodorebugnet ,

Unfortunately we don't support this sort of historic query since we're only storing the final state rather than the transitions of entites. You would need to do exactly as you suggest, create a `historicKitty` entity (one to many mapping to the `kitty` entity) to store this historic state.
