### ISSUE TITLE
[usage question] Where does schema.graphql come from?

### ISSUE THREAD

**Issue by paulvi** [subquery/subql#361]
I have read through docs, they are well written and easy to understand,
and it should be so for any familiar with TheGraph.
However, I could not find anything that is most valuable for DeFi developer, that is relation with Solidity smart contracts.

From https://doc.subquery.network/quickstart/quickstart.html#graphql-model-generation

> In order to `index` (opens new window)your SubQuery project, you must first generate the required GraphQL models that you have defined in your GraphQL Schema file (`schema.graphql`).

Now where this `schema.graphql` come from?
Should it be written manually?

Even if I write it manually, who data will be populated from smart contract? There is no any smart contract deployment address specification.

I checked https://github.com/subquery/subql-examples/tree/main/kitty that should be based on some smart contract data, but I could not see any smart contract references.

**Comment by ianhe8x** [comment]
It is manually written, and the struct of entities in the schema doesn't have to be same as your on-chain data, rather should be designed dedicatedly for the query scenario.
By smart contract if you mean evm smart contract, first not all substrate-based chain supports it, and there are subtle differences among these chains. In short, it is not supported by subql, though it can be achieved at some level since contract events are also normal chain events.
If it is WASM contract, we reckon it is still in very early stage, so we haven't start supporting it yet.

**Comment by paulvi** [comment]
OK, "manually written"

**Comment by jamesbayly** [comment]
@paulvi as Ian mentioned, you have the freedom to decide the format of your data store and you can quickly define this using the `schema.graphql` file. There is no way for us to predict what data you want to store or save. You can learn more on our [guides](https://doc.subquery.network/create/graphql.html)
