### ISSUE TITLE
Error Getting Finalised Block from OnFinality RPC

### ISSUE THREAD

**Issue by jamesbayly** [subquery/subql#472]
![2021-09-13 21 12 05](https://user-images.githubusercontent.com/46693720/133057301-babcc214-2433-47a4-9328-bae6df5a255e.jpg)

**Comment by ianhe8x** [comment]
could be related. We will need to test it on a dedicated node with logs enabled
![image](https://user-images.githubusercontent.com/39037239/133058800-030e41dd-b386-47c4-af4b-8566eb90af17.png)

**Comment by ianhe8x** [comment]
Usually this error shouldn't be a bother, because polkadot-js api will try reconnect the ws connection. And it looks like a server-side issue that under heavy load chain-node might disconnect the ws. 
A workaround is to use http endpoint instead of ws one. I merged a PR to support that, will be available in next release

**Comment by ianhe8x** [comment]
https://github.com/paritytech/substrate/issues/9811

**Comment by jiqiang90** [comment]
This is fixed
