### ISSUE TITLE
Add redis cache to query service

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#502]
- [ ] control it through flag
- [ ] use cache for postgres query,  identify query by md5

**Comment by zhex** [comment]
background:
the cache is always a useful solution to reduce the pressure on the database in a web app. for subquery query service we also should provide a cache layer. 

We can use graphql payload as a unique identifier for the cache. Because the subquery project is public-facing, every query payload should return the same result in a particular time duration, so this can cover most of the cases.

the cache can be live as express middleware
- we can support both in-memory cache and Redis cache
- it converts the incoming payload into a hash key with the MD5 algorithm or alternative (fast and fixed-width). 
- user can set the TTL for the cache
- user can allocate the max-storage size for the service
- user can give a key prefix for the Redis cache key to support multiple projects

**Comment by jiqiang90** [comment]
This can be closed now, cache is added by host side
