### ISSUE TITLE
Build a template registry and allow template selection for `subql init`

### ISSUE THREAD

**Issue by ianhe8x** [subquery/subql#535]
When execute `subql init`, add some interactions to let user select a template (from a remote template registry).
or user add `--tpl xxx` to specify which one to use.

We can engage with parachain teams, let them maintain their own template to benefit their community.

**Comment by wqsz7xn** [comment]
haskell stack does this quite well using 
https://github.com/commercialhaskell/stack-templates

**Comment by wqsz7xn** [comment]
I'm going to take the same approach as haskell stack above except to use handlebars instead of mustache because I think this approach is good.

Outline:
- Make a small library that allows people to point it towards a project and generate a template, this will generate a single handlebars file containing all the files of the template This can be built as a wrapper into `subql-cli` to generate. 
- They then submit the handlebars file to the template repo for us to verify, merge and everyone can then use that template

Reasoning:
- Subquery controls all project templates which eliminates possible arbitrary code
- Very easy templating, can easily replace details of projects such as authors and other configuration fields as necessary
- Makes it easy for others to generate project templates and submit them

Subtasks:
- Add a `--git` flag to the cli so that people can just download

**Comment by wqsz7xn** [comment]
https://github.com/subquery/templates
And CLI changes have been merged. We just need a release which is happening today
