### ISSUE TITLE
Performance improvement

### ISSUE THREAD

**Issue by jiqiang90** [subquery/subql#566]
- [x] Reduce rpc call getRuntimeVersion ,it currently been called in 3 different places

https://github.com/subquery/subql/blob/f15ebc463d14a736781484f5ec63ef3a7c6a33e5/packages/node/src/utils/substrate.ts#L304
https://github.com/subquery/subql/blob/f15ebc463d14a736781484f5ec63ef3a7c6a33e5/packages/node/src/indexer/api.service.ts#L141
https://github.com/subquery/subql/blob/f15ebc463d14a736781484f5ec63ef3a7c6a33e5/packages/node/src/indexer/fetch.service.ts#L349

- [x] Use dictionary specVersion

**Comment by stwiname** [comment]
[ ] Update next block height once per batch of blocks rather than each block

If `--debug` is set then this gets logged the number of batch size, meaning 30 (default) DB writes per batch, this could be reduced to one by using the highest block of a batch 
`subquery-node_1   | 2021-11-16T06:41:06.341Z <db> DEBUG Executing (5b5d39e9-f571-487d-a64a-35d71d78fddb): START TRANSACTION;
subquery-node_1   | 2021-11-16T06:41:06.512Z <db> DEBUG Executing (5b5d39e9-f571-487d-a64a-35d71d78fddb): UPDATE "subqueries" SET "next_block_height"=$1,"updated_at"=$2 WHERE "id" = $3
subquery-node_1   | 2021-11-16T06:41:06.512Z <db> DEBUG Executing (5b5d39e9-f571-487d-a64a-35d71d78fddb): COMMIT;`

**Comment by ianhe8x** [comment]
@stwiname batch-size is used for fetching and preparing blocks, no db writes involved. We open a transaction for each block's processing, so it's not likely can be optimized.

**Comment by jiqiang90** [comment]
See https://github.com/subquery/subql/pull/1046, this can be closed now
