### ISSUE TITLE
how to support multiple subquery projects?

### ISSUE THREAD

**Issue by dengpan1** [subquery/subql#653]
“subql-node -f your-project-path " a project must be specified , how to support multiple subquery projects?

**Comment by ianhe8x** [comment]
One subql-node instance can only index one project, if you have more projects to be indexed you just run more subql-nodes.
This is by design and also a limitation of nodejs. We have seen a large mem usage when indexing for one project, and nodejs can only handle limited memory (2g maximum). So we are not likely to support multiple projects in one instance.
