### ISSUE TITLE
Remove polkadot dependencies from node-terra

### ISSUE THREAD

**Issue by stwiname** [subquery/subql#957]

**Comment by jiqiang90** [comment]
It been used in hash the poiBlock and hash the enumName, 


- https://github.com/subquery/subql/blob/3f155823893f73f375a3db4da40c9c518ebe1abb/packages/node-terra/src/indexer/store.service.ts#L229
- https://github.com/subquery/subql/blob/3f155823893f73f375a3db4da40c9c518ebe1abb/packages/node-terra/src/indexer/PoiBlock.ts#L18

since both `node` and `node-terra` are using this, do you suggest we can move this into a common package
